region               = "us-east-1"
az                   = ["us-east-1a", "us-east-1b"]
alb_name             = "app-alb"
db-username          = "admin"
db-password          = "global!23"
cfn_stack_name       = "asg-rolling"
cfn_signal_count     = 3
asg_max_size         = 4
asg_min_size         = 2
asg_desired_capacity = 2